#!/bin/sh
# configurator - System software and environment bootstrapping for macOS.
# TODO: Make this installer script multi-platform and multi-shell compatible.

# Usage message.
usage() {
  tee <<EOF
Usage: $0 [OPTIONS]

OPTIONS:
  --username, -u <github-username>   Specify your GitHub username.
  --help, -h                         Show this help message and exit.

If no username is provided, the script will prompt for it interactively.
For more information, see https://github.com/karimbenbourenane/macos-installer
EOF
}

if [ $# -gt 2 ]; then
  echo "Error: Too many arguments. At most two arguments are allowed."
  usage
  exit 1
fi

# Default GitHub username.
_github_username=""

# Parse command-line arguments.
case "$1" in
--username | -u)
  shift
  _github_username="$1"
  ;;
--help | -h)
  usage
  exit 0
  ;;
*)
  echo "Invalid option: $1"
  usage
  exit 1
  ;;
esac

# If no username is provided, prompt the user.
if [ -z "${_github_username}" ]; then
  echo "Enter your GitHub username: "
  read -r _github_username
fi

# Begin installation.
echo "Begin system configurator..."
echo "See https://github.com/karimbenbourenane/macos-installer for more info."

# Install the Command Line Tools for Xcode.
echo "Installing Command Line Tools..."
xcode-select --install

# Create system Python symlinks.
echo "Creating system Python symlinks..."
sudo install -m 755 /dev/stdin /usr/local/bin/python <<'EOF'
#!/bin/sh
exec "$(xcode-select -p || true)/usr/bin/python3" "$@"
EOF
sudo install -m 755 /dev/stdin /usr/local/bin/pip <<'EOF'
#!/bin/sh
exec "$(xcode-select -p || true)/usr/bin/pip3" "$@"
EOF

# Enable Touch ID for sudo.
echo "Enabling Touch ID for sudo..."
sudo sh -c 'cp /etc/pam.d/sudo_local.template /etc/pam.d/sudo_local'
sudo sh -c 'sed -i "" "s/^#auth/auth/" /etc/pam.d/sudo_local'

# Install chezmoi.
echo "Installing chezmoi and dotfiles..."
sh -c "$(curl -fsLS get.chezmoi.io || true)" \
  -- -b "$(mktemp -d || true)" init "${_github_username}" --ssh --apply

# Create Developer directory for code repositories.
echo "Creating user Developer directory..."
mkdir -p "${HOME}"/Developer

# Create XDG directories.
echo "Creating XDG directories..."
mkdir -p "${HOME}"/.config
mkdir -p "${HOME}"/.local/bin
mkdir -p "${HOME}"/.local/share
mkdir -p "${HOME}"/.local/state

# Load XDG logout script.
echo "Loading XDG logout script..."
_xdg_logout="${HOME}"/Library/LaunchAgents/org.freedesktop.specifications.plist
launchctl load "${_xdg_logout}"

# Set Zsh configuration directory globally to use standard XDG location.
echo "Setting Zsh configuration directory globally..."
# TODO: backup the original file if it already exists.
sudo sh -c 'tee -a /etc/zshenv >/dev/null' <<'EOF'
# Handle ZDOTDIR when it is set but not to the standard path for Zsh config.
if [ -n "${ZDOTDIR-}" ] && [ "${ZDOTDIR}" != "${HOME}"/.config/zsh ]; then
    # Tell JetBrains IDEs the standard ZDOTDIR path when using a custom one.
    JETBRAINS_INTELLIJ_ORIGINAL_ZDOTDIR="${HOME}"/.config/zsh
else
    # Set ZDOTDIR to the standard path for Zsh config.
    ZDOTDIR="${HOME}"/.config/zsh
fi
EOF

# Set GitHub content base URL to keep script paths short.
_content_base_url="https://raw.githubusercontent.com"

# Install Oh My Zsh.
echo "Installing Oh My Zsh..."
export ZDOTDIR="${HOME}/.config/zsh"
export ZSH="${HOME}/.local/share/ohmyzsh"
curl -fsSL "${_content_base_url}/ohmyzsh/ohmyzsh/master/tools/install.sh" | sh

# Install Homebrew.
echo "Installing Homebrew..."
curl -fsSL "${_content_base_url}/Homebrew/install/HEAD/install.sh" | bash
_brew_prefix=${HOMEBREW_PREFIX:-$(brew --prefix || echo /usr/local)}

# Install bundles (system packages and desktop apps).
echo "Installing Homebrew bundles..."
brew bundle --file "${HOME}/.config/homebrew/Brewfile" install
sudo mkdir -p /usr/local/lib
sudo install -m 755 "${_brew_prefix}"/lib/libykcs11.dylib /usr/local/lib

# Fix permissions for some Homebrew packages on Apple Silicon.
if [ -d "${_brew_prefix}/share" ]; then
  echo "Fixing permissions for Homebrew packages..."
  chmod -R go-w "${_brew_prefix}/share"
fi

# Load unlinking scripts.
echo "Loading Google Drive unlink script..."
launchctl load "${HOME}"/Library/LaunchAgents/local.unlink-google-drive.plist
echo "Loading Python unlink script..."
launchctl load "${HOME}"/Library/LaunchAgents/local.unlink-python.plist

# Check local JetBrains scripts.
echo "Checking local scripts..."
if brew list pycharm >/dev/null 2>&1; then
  _pycharm_path="${HOME}/.local/bin/pycharm"
  if [ -f "${_pycharm_path}/" ]; then
    chmod +x "${HOME}/.local/bin/pycharm"
    _pycharm_status="can be found at"
    echo "PyCharm script can be found at ${_pycharm_path}."
  else
    _pycharm_status="is missing from"
  fi
  echo "PyCharm script ${_pycharm_status} ${_pycharm_path}."
else
  echo "PyCharm is not installed."
fi

# Install all vim-plug plugins.
echo "Installing vim-plug plugins..."
vi -Esu "${HOME}/.config/vim/vimrc" +quitall

# Install Github Copilot for command line.
echo "Installing Github Copilot for command line..."
gh extension install github/copilot-cli --force

# Prevent macOS Finder from creating .DS_Store files on network shares
echo "Preventing macOS Finder from creating .DS_Store files on network shares..."
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool TRUE

# Complete installation.
echo "System configurator completed."
echo "Please open a new shell session to complete the installation."
